### ISSUE TITLE
Remove size specifiers on asm files;

### ISSUE THREAD

**Issue by bsdinis** [intel/cryptography-primitives#10]
`nasm` complains when some `lea` ops get a size specifier;
Removing them in the following locations (in the `build` dir after cmake) fixes the issue:

    asm_sources/n0/asm_intel64/pcpsha256l9as.asm:486
    asm_sources/n0/asm_intel64/pcpsha256l9as.asm:514
    asm_sources/n0/asm_intel64/pcpsha512l9as.asm:486

    asm_sources/k0/asm_intel64/pcpsha256l9as.asm:486
    asm_sources/k0/asm_intel64/pcpsha256l9as.asm:514
    asm_sources/k0/asm_intel64/pcpsha512l9as.asm:486

    asm_sources/l9/asm_intel64/pcpsha256l9as.asm:486
    asm_sources/l9/asm_intel64/pcpsha256l9as.asm:514
    asm_sources/l9/asm_intel64/pcpsha512l9as.asm:486

**Comment by amatyuko** [comment]
You are correct, the size specifier is not required here, thanks.

But anyway as I said in the issue #11 the minimal supported NASM version is 2.15 (which does not complain about size specifier anymore). This version is not released yet, but you can find the working developer snapshot [here](https://www.nasm.us/pub/nasm/snapshots/20191023/).
