### ISSUE TITLE
Add information about FIPS-140-2 compliance

### ISSUE THREAD

**Issue by elazarl** [intel/cryptography-primitives#12]
In many organization, the question whether or not there's an updated version which is officially FIPS-140-2 compliant.

Can you clarify the situation in the documentation?

**Comment by skirillo** [comment]
Thank you for notice. Sure this info will be added

**Comment by elazarl** [comment]
Thanks,
@skirillo can you please ping me (or in this bug) when it's done?

**Comment by skirillo** [comment]
sure, I will.
