### ISSUE TITLE
Missing file asmdefs.inc

### ISSUE THREAD

**Issue by alex-111-gh** [intel/cryptography-primitives#14]
We've tried to build the library. 
`CC=gcc CXX=g++ cmake CMakeLists.txt -B_build -DARCH=intel64`
In the end of the hoops and jumps, it barfs out:

> [ 12%] Built target ippcp_s_m7
[ 12%] Building ASM_NASM object sources/ippcp/CMakeFiles/ippcp_s_n8-asmobjs.dir/__/__/asm_sources/n8/asm_intel64/cpinitas.asm.o
/home/at/Dev/ipp-crypto/_build/asm_sources/n8/asm_intel64/cpinitas.asm:17: fatal: unable to open include file `asmdefs.inc'
sources/ippcp/CMakeFiles/ippcp_s_n8-asmobjs.dir/build.make:79: recipe for target 'sources/ippcp/CMakeFiles/ippcp_s_n8-asmobjs.dir/__/__/asm_sources/n8/asm_intel64/cpinitas.asm.o' failed
make[2]: *** [sources/ippcp/CMakeFiles/ippcp_s_n8-asmobjs.dir/__/__/asm_sources/n8/asm_intel64/cpinitas.asm.o] Error 1
CMakeFiles/Makefile2:205: recipe for target 'sources/ippcp/CMakeFiles/ippcp_s_n8-asmobjs.dir/all' failed
make[1]: *** [sources/ippcp/CMakeFiles/ippcp_s_n8-asmobjs.dir/all] Error 2
Makefile:100: recipe for target 'all' failed
make: *** [all] Error 2

as if it misses/can't find asmdefs.inc.
This is somewhat strange, since it can be found in `ipp-crypto/sources/include/asmdefs.inc`.
Please advise. Thank you!

**Comment by amatyuko-intc** [comment]
Hello,

Could you try to build it with [this](https://www.nasm.us/pub/nasm/snapshots/20191023/) NASM version?

Regards,
Andrey

**Comment by alex-111-gh** [comment]
Perfect! Thanks Andrey.
It is indeed an issue between dated (nasm 2.13) and gcc-8 on ubuntu. Moving to 2.15rc solves the compilation issue.
