### ISSUE TITLE
crypto_mb: is OPENSSL_USE_STATIC_LIBS necessary?

### ISSUE THREAD

**Issue by mythi** [intel/cryptography-primitives#17]
I'm building ipp-crypto on Clear Linux which does not provide static libs in its openssl dev package. 

Due to https://github.com/intel/ipp-crypto/blob/develop/sources/ippcp/crypto_mb/CMakeLists.txt#L39 CMake fails. However, the build works OK if I just drop that line.

**Comment by ElenaTyuleneva** [comment]
Hello Mikko,

Can you, please, provide us CMake output with the error you obtained during library configuration? With this information it will be easier for me to analyze the problem.

Thanks,
Elena

**Comment by mythi** [comment]
@ElenaTyuleneva the problem is known: I don't have the static libs and this Cmake rule makes the build fail:

```
Make Error at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY)
  (Required is at least version "1.1.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.17/Modules/FindOpenSSL.cmake:450 (find_package_handle_standard_args)
  CMakeLists.txt:40 (find_package)
```

If I remove that line the build succeeds. My ask is why is that needed?

**Comment by skirillo** [comment]
Seems the discussed issue rose in connection with build of "crypto_mb" validation tests.
If so, then the answer is very easy - this is the decision of test developer. These tests are basically for developer's purpose. Of course, it can be used as sample of usage. But in this case, it seems, one should adhere to the logic of the developer. Every one permitted to link own application any way it like - statically or dynamically.

**Comment by mythi** [comment]
@skirillo I don't think you answered my question

**Comment by ElenaTyuleneva** [comment]
Using static linkage is not a required condition. We chose this type of linkage so that the obtained tests are completely autonomous and contain all the necessary dependencies. 

So the answer on your question: OPENSSL_USE_STATIC_LIBS variable is not necessary. Which type of linkage to use - static or dynamic - is up to you.

**Comment by skirillo** [comment]
It seems to me that we deviated for technical side.
Let me ask you, do you consider discussed subject as an real issue in the build script?
If so, please state your claim clearly or propose solution that you think is 100% correct.

**Comment by mythi** [comment]
> If so, please state your claim clearly or propose solution that you think is 100% correct.

My proposal is in #18

**Comment by ElenaTyuleneva** [comment]
Hi Mikko,

Pull request [#18](https://github.com/intel/ipp-crypto/pull/18) was merged in our 'develop' branch. Thank you for your proposal and interest to Crypto multi-buffer library. 

Elena
