### ISSUE TITLE
Why don't include SM2 public key encryption algorithm?

### ISSUE THREAD

**Issue by chinsyo** [intel/cryptography-primitives#2]
Both SM3 and SM4 are included. Can anyone explain why not SM2?

**Comment by skirillo** [comment]
Chinsyo, I see in IPP Crypto the the following SM2 oriented functionality:
1) ippsGFpECInitStdSM2 - init parameters of Elliptic Curve as defined in SMx std
2) ippsGFpECSignSM2/ippsGFpECVerifySM2 - signature generation and verification as in SMx std
3) set of functions ippsGFpECES{GetSize/Init/SetKey/Start/Encrypt/Decrypt/Final}_SM2 for enc/dec as defined in SMx std.
See https://software.intel.com/ipp-crypto-reference for details.

Could you be more exact what "SM2" did you mean in your message?
