### ISSUE TITLE
Build issue Ubuntu-18.04LTS

### ISSUE THREAD

**Issue by geobon** [intel/cryptography-primitives#25]
CMake Error at CMakeLists.txt:53 (find_package):

  Could not find a package configuration file provided by "Python" with any
  of the following names:

    PythonConfig.cmake
    python-config.cmake

I have python-dev and cmake installed  No files with these names anywhere on the filesystem of this machine.

**Comment by amatyuko-intc** [comment]
Ubuntu 18.04 LTS has default cmake version 3.10. 
The project's minimal supported version is 3.12.
Please try to update it.

At the same time I see that the check for minimal version is outdated in project's cmake scripts, so it accepts 3.10.
We will fix it. Thanks.

Regards,
Andrey
