### ISSUE TITLE
Dispatcher code cannot be generated successfully on Windows

### ISSUE THREAD

**Issue by lzha101** [intel/cryptography-primitives#26]
Tried to build IPP crypto on Windows with below command following the [BUILD.md](https://github.com/intel/ipp-crypto/blob/develop/BUILD.md#building-intel-ipp-cryptography-on-windows-os) :
```
cmake CMakeLists.txt -B_build -G"Visual Studio 16 2019" -Ax64
```
This command generated the .sln file and project files successfully. But it also reports below python syntax error and results in the dispatcher assembly code not generated successfully.

> SyntaxError: Non-ASCII character '\xc2' in file C:/sgx_source/ipp_git_repo/git/ipp-crypto/sources/dispatcher/gen_disp_win64.py on line 18, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

It is caused by the line:
https://github.com/intel/ipp-crypto/blob/bb8b68c6a9147debba402046540440eaba3c2f90/sources/dispatcher/gen_disp_win64.py#L18

Changing Intel® to Intel(R) in the script could solve the python syntax error.

**Comment by ElenaTyuleneva** [comment]
This problem may occur with Python2, which has officially reached EOL status. 
The issue should be resolved by using Python3 to generate dispatcher.

Regards,
Elena

**Comment by lzha101** [comment]
@ElenaTyuleneva yes, I'm exactly using Python2 according to https://github.com/intel/ipp-crypto/blob/develop/BUILD.md#common-tools.

**Comment by ElenaTyuleneva** [comment]
Seems like we have outdated info in our software requirements list. 
It will be corrected, sorry for the inconvenience.

Elena
