### ISSUE TITLE
Uninitialized variables are used

### ISSUE THREAD

**Issue by LukaszKwidzinski** [intel/cryptography-primitives#3]
Static code analysis return Critical errors.

C:\ipp-crypto\sources\ippcp\pcprij128safe.c:177 UNINIT.STACK.ARRAY.PARTIAL.MUST (1:Critical) Analyze
'blk_lo' array elements are used uninitialized in this function with index range: [2,15].

C:\ipp-crypto\sources\ippcp\pcprij128safe.c:178 UNINIT.STACK.ARRAY.PARTIAL.MUST (1:Critical) Analyze
'blk_hi' array elements are used uninitialized in this function with index range: [2,15].

C:\ipp-crypto\sources\ippcp\pcprij128safe.c:232 UNINIT.STACK.ARRAY.PARTIAL.MUST (1:Critical) Analyze
'blk_lo' array elements are used uninitialized in this function with index range: [2,15].

C:\ipp-crypto\sources\ippcp\pcprij128safe.c:233 UNINIT.STACK.ARRAY.PARTIAL.MUST (1:Critical) Analyze
'blk_hi' array elements are used uninitialized in this function with index range: [2,15].

**Comment by PavelBerdnikOFF** [comment]
Hi, which tool do you use for static code analysis?
Pavel.

**Comment by LukaszKwidzinski** [comment]
We're using Klocwork.
Lint is good enough too.

**Comment by LukaszKwidzinski** [comment]
Hi,

We use Klockwork.
Lint is also good and is open source.

Br,
Lukasz

**Comment by skirillo** [comment]
Hi, Lucasz,
I think you meant the following piece of source:
void TransformNative2Composite(Ipp8u out[16], const Ipp8u inp[16])
{
   Ipp8u blk_lo[16], blk_hi[16];
   ((Ipp64u*)blk_lo)[0] = ((Ipp64u*)inp)[0] & 0x0F0F0F0F0F0F0F0F;
   ((Ipp64u*)blk_lo)[1] = ((Ipp64u*)inp)[1] & 0x0F0F0F0F0F0F0F0F;
   ((Ipp64u*)blk_hi)[0] = (((Ipp64u*)inp)[0]>>4) & 0x0F0F0F0F0F0F0F0F;
   ((Ipp64u*)blk_hi)[1] = (((Ipp64u*)inp)[1]>>4) & 0x0F0F0F0F0F0F0F0F;
   {
      int n;
      for(n=0; n<16; n++) {
         Ipp8u lo = Native2CompositeTransformationLO[blk_lo[n]];
         Ipp8u hi = Native2CompositeTransformationHI[blk_hi[n]];
         out[n] = lo^hi;
      }
   }
}
But I don't see any  "uninitialized in this function with index range: [2,15]".
Really, the lines
   ((Ipp64u*)blk_lo)[0] = ((Ipp64u*)inp)[0] & 0x0F0F0F0F0F0F0F0F;
   ((Ipp64u*)blk_lo)[1] = ((Ipp64u*)inp)[1] & 0x0F0F0F0F0F0F0F0F;
   ((Ipp64u*)blk_hi)[0] = (((Ipp64u*)inp)[0]>>4) & 0x0F0F0F0F0F0F0F0F;
   ((Ipp64u*)blk_hi)[1] = (((Ipp64u*)inp)[1]>>4) & 0x0F0F0F0F0F0F0F0F;
assign both blk_lo[16] and blk_hi[16] to 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F, 0F.
Believe the KW did not recognize casting statements.
But this is KW issue, but not ipp crypto source code.
Do you agree?
