### ISSUE TITLE
memory leak in example code

### ISSUE THREAD

**Issue by xhuan28** [intel/cryptography-primitives#35]
I notice that there is a potential memory leak risk in the [example](https://github.com/intel/ipp-crypto/blob/develop/examples/utils/bignum.cpp):
[Line156](https://github.com/intel/ipp-crypto/blob/develop/examples/utils/bignum.cpp#L156):   

> delete (Ipp8u*)m_pBN;

should be 

> delete[] (Ipp8u*)m_pBN;  

to match 

> m_pBN = (IppsBigNumState*)( new Ipp8u[size] );

**Comment by ifedyaev** [comment]
Hi,

thank you for contacting us. We'll fix it in the next release.

**Comment by amatyuko-intc** [comment]
The problem is fixed. Thanks for submitting an issue.
