### ISSUE TITLE
Does the latest release support new instructions for ICX?

### ISSUE THREAD

**Issue by xhuan28** [intel/cryptography-primitives#36]
For example, VPMADD52 and VAES. Thanks.

**Comment by ifedyaev** [comment]
Hi,
thanks for the question!

IPP Crypto supports ICX instructions For example, there is a part of the library, such as [Crypto_MB](https://software.intel.com/content/www/us/en/develop/documentation/ipp-crypto-reference/top/multi-buffer-cryptography-functions.html), which is completely built for ICX+ processors and, as expected, [VPMADD52*](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=vpmadd52*) optimization. In IPPCP, all AES algorithms are optimized for [VAES*](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=vaes*) instructions.

If you are interested in any specific functions, then write below, I will be happy to answer you.

**Comment by xhuan28** [comment]
Thanks for your prompt answer. I notice that there is a ModExp using multi-buffer. Is there any multi-buffer function for ModMul and ModAdd?

**Comment by ifedyaev** [comment]
Hi,
Thank you for your interest

We have a 1k, 2k, 3k, 4k implementation for ModExp in Crypto_MB. Unfortunately ModAdd ModMul is not represented in the open API. If it's not difficult for you, please explain what you want to implement? Perhaps we can help you with this.

**Comment by xhuan28** [comment]
I have another question. Is there any example about how to generate RSA key pair by `ippsRSA_GenerateKeys()`. Per my understanding, I have to allocate memory for `pModulus`, `pPublicExp` and `pPrivateExp` respectively before call `ippsRSA_GenerateKeys()`, right? If the bit size of `n` is 1024 and the bit size of `e` is 16, I can allocate memory for `pModulus` and `pPublicExp` easily. However, how can I allocate memory for `pPrivateExp` as I don't know the bit size of `d`. Is there any relationship between the bit size of `n`, `e` and `d`? Thanks.

**Comment by ElenaTyuleneva** [comment]
Closing the issue since there was no answer provided for a long time.
@xhuan28 , feel free to contact us if any other questions appear.
