### ISSUE TITLE
Cerfication support for the IPP

### ISSUE THREAD

**Issue by syan10** [intel/cryptography-primitives#37]
Hi,
I notice that it mentioned below in the Readme file.
"
Intel IPP Cryptography library is not certified for FIPS-140-2 (Security Requirements for Cryptographic Modules) and CMVP (Cryptographic Module Validation Program).
"

Does the IPP plan to certify the FIPS-140-2 in future release?

**Comment by amatyuko-intc** [comment]
Hi, @syan10, there're plans to add capabilities to make the library certifiable, i.e. FIPS-140-3 ready to be able pass validation as part of user's product. There are no plans to certificate the library as a standalone.

**Comment by syan10** [comment]
thanks for the quick reply.

So does the currently version already can be certifiable for FIPS-140-3 as part of user's product?  or when does it can support it?

**Comment by amatyuko-intc** [comment]
It hasn't been tested against ACVP, so currently it is up to user to check it, as well as provide other capabilities required by FIPS 140-3.  There will be ongoing efforts towards FIPS ready early next year. We will update information about it, when status is changed.

**Comment by syan10** [comment]
It's great!!

Thanks for the information. :)

**Comment by amatyuko-intc** [comment]
Feel free to contact us if you have any other questions.
