### ISSUE TITLE
 error: invalid conversion from ‘int8u**’ {aka ‘unsigned char**’} to ‘const int8u**’ {aka ‘const unsigned char**’} [-fpermissive]

### ISSUE THREAD

**Issue by xhuan28** [intel/cryptography-primitives#41]
If I pass a `int8u* array[16`] to `mbx_sm3_msg_digest_mb16()`, there is an issue 
> error: invalid conversion from ‘int8u**’ {aka ‘unsigned char**’} to ‘const int8u**’ {aka ‘const unsigned char**’} [-fpermissive]

If I change the definition below
https://github.com/intel/ipp-crypto/blob/3ae57715fbc7383ef527cab0b824d736b60fa06d/sources/ippcp/crypto_mb/include/crypto_mb/sm3.h#L55
to
`EXTERN_C mbx_status16 mbx_sm3_msg_digest_mb16(const int8u* const msg_pa[16],   `

The issue disappears.

**Comment by ElenaTyuleneva** [comment]
Hi, 
Thank you for reporting this issue, we started working on it.

**Comment by ElenaTyuleneva** [comment]
@xhuan28 ,  This API issue was fixed starting with [IPP Crypto 2021.7](https://github.com/intel/ipp-crypto/releases/tag/ippcp_2021.7) release so the problem should have been eliminated.
I'm sorry for the late notification!

Please open another question if you still face any problems.

**Comment by yellow123Nike** [comment]
Do you use ifma_mb8_to_HexStr8() please? I always get an error when I convert from mb8 to string8
