### ISSUE TITLE
Relax cmake version requirement

### ISSUE THREAD

**Issue by mrx23dot** [intel/cryptography-primitives#43]
This is the latest version that ubuntu has of cmake, it should be enough to build a simple library.

```
CC=gcc CXX=g++ cmake CMakeLists.txt -B_build -DARCH=intel64
CMake Error at CMakeLists.txt:21 (cmake_minimum_required):
  CMake 3.12 or higher is required.  You are running version **3.10.2**
```

**Comment by mrx23dot** [comment]
Also libtomcrypt dependency is not mentioned in readme:

```
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
/sbin/ldconfig.real: /usr/lib/libtomcrypt.so.1 is not a symbolic link

```

**Comment by aelizaro** [comment]
Hi @mrx23dot, sorry for the super-delayed responce! Thank you for the notes, we will investigate how we can improve CMake part.

**Comment by paveldyakov** [comment]
Hi @mrx23dot, I would like to notify you that in the coming IPP Crypto release we update the minimal required OpenSSL version to OpenSSL 3.0.

OpenSSL 3.0 requires CMake 3.18 as the minimal version. So that we have to increase the minimal required CMake version to 3.18.

Sorry for inconvenience.
