### ISSUE TITLE
Ubuntu Server 22.04 make all error

### ISSUE THREAD

**Issue by jimthedj65** [intel/cryptography-primitives#45]
Hi all,

Running on a C3000 Intel C3958 to be exact Atom platform with latest QAT drivers installed.

Downloaded the repo today and ran 
CC=gcc CXX=g++ cmake . -B"../build" -DARCH=intel64 -DCMAKE_INSTALL_PREFIX=/home/mypath/libcrypto_mb/installation -DMERGED_BLD:BOOL=off -DPLATFORM_LIST="l9;k0"

Result:
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE is unset, defaulting to Release
-- Found Python: /usr/bin/python3.10 (found version "3.10.6") found components: Interpreter
-- CMAKE_VERSION ......................... 3.22.1
-- NONPIC_LIB ............................ off
-- PROJECT ............................... Intel® Integrated Performance Primitives Cryptography (Intel® IPP Cryptography)
-- CMAKE_BINARY_DIR ...................... /home/mypath/build
-- CMAKE_OUTPUT_DIR ...................... /home/mypath/build/.build
-- CMAKE_SOURCE_DIR ...................... /home/mypath/ipp-crypto
-- IPP_CRYPTO_DIR ........................ /home/mypath/ipp-crypto
-- CMAKE_GENERATOR ....................... Unix Makefiles
-- CMAKE_C_COMPILER_ID ................... GNU
-- CMAKE_CXX_COMPILER_ID ................. GNU
-- IPP_CRYPTO_INCLUDE_DIR ................ /home/mypath/ipp-crypto/include
-- IPP_CRYPTO_SOURCES_INCLUDE_DIR ........ /home/mypath/ipp-crypto/sources/include
-- IPP_CRYPTO_SOURCES_DIR ................ /home/mypath/ipp-crypto/sources/ippcp
-- ARCH .................................. intel64
-- DYNAMIC_LIB ........................... ON
-- CMAKE_INSTALL_PREFIX .................. /home/mypath/libcrypto_mb/installation
-- PYTHON_VERSION_STRING ................. 3.10.6
-- MERGED_BLD ............................ off
-- BUILD_EXAMPLES ........................ off
-- Platform list ......................... l9k0
-- Using compiler options from ........... /home/mypath/ipp-crypto/sources/cmake/linux/GNU8.2.0.cmake
-- The ASM_NASM compiler identification is YASM
-- Found assembler: /usr/bin/yasm
-- ASM compiler version .................. /usr/bin/yasm
-- ASM object format ..................... elf64
-- CMAKE_BUILD_TYPE is not set to Debug explicitly, defaulting to Release
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "3.0.2", minimum required is "1.1.0")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mypath/build

when entering the build directory and running
make all 

I get an error 

Scanning dependencies of target ippcp_dyn_l9-asmobjs
[  0%] Building ASM_NASM object sources/ippcp/CMakeFiles/ippcp_dyn_l9-asmobjs.dir/__/__/asm_sources/l9/asm_intel64/l9_aes_keyexp_128.asm.o
/home/mypath/ipp-crypto/sources/include/ia_common.inc:21: error: unknown preprocessor directive `%use'
/home/mypath/ipp-crypto/sources/include/ia_common.inc:21: error: label or instruction expected at start of line
/home/mypath/ipp-crypto/sources/include/ia_common.inc:21: error: instruction expected after label
make[2]: *** [sources/ippcp/CMakeFiles/ippcp_dyn_l9-asmobjs.dir/build.make:75: sources/ippcp/CMakeFiles/ippcp_dyn_l9-asmobjs.dir/__/__/asm_sources/l9/asm_intel64/l9_aes_keyexp_128.asm.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:146: sources/ippcp/CMakeFiles/ippcp_dyn_l9-asmobjs.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

I have checked all dependencies as much as I can; any assistance is greatly appreciated.

**Comment by amatyuko** [comment]
I noticed that 'yasm' is picked up as assembler. Please make sure that 'nasm' (version at least 2.15) is in the PATH. It is the only supported assembler according to [SW requirements](https://github.com/intel/ipp-crypto/blob/develop/BUILD.md#common-tools).

**Comment by jimthedj65** [comment]
> I noticed that 'yasm' is picked up as assembler. Please make sure that 'nasm' (version at least 2.15) is in the PATH. It is the only supported assembler according to [SW requirements](https://github.com/intel/ipp-crypto/blob/develop/BUILD.md#common-tools).

Thanks I will make sure that's corrected thanks for the heads up.

**Comment by andreyfe1** [comment]
Hi @jimthedj65
Do you still see an error? Is the issue still relevant?

**Comment by andreyfe1** [comment]
Closing since no response. Please, reopen it if it is still relevant
