### ISSUE TITLE
Add more functions for crypto_mb , such as inverse

### ISSUE THREAD

**Issue by cyjseagull** [intel/cryptography-primitives#51]

**Comment by paveldyakov** [comment]
Hi @cyjseagull, 
Sorry for the delay in response. 

The request is a little bit unclear for me. Could you please provide more details? 
Like: the list of functions, applications that require such support, any other important aspects?

Such information will help us a lot to analyze this request.

**Comment by paveldyakov** [comment]
Hi @cyjseagull
Please let us know if the topic is still relevant for you.

**Comment by paveldyakov** [comment]
Closing the issue because of no response. Please feel free to reopen it if it is still relevant
