### ISSUE TITLE
Does IPPCrypto support oneAPI programming model and offload to GPU?

### ISSUE THREAD

**Issue by xhuan28** [intel/cryptography-primitives#52]
Hi, as I notice IPPCrypto is a part of oneAPI base toolkit, can I offload some workloads that are developed with IPPCrypto API to Intel GPU by using oneAPI programming model?  As far as I know, oneMKL has already supported this. Thanks.

**Comment by ElenaTyuleneva** [comment]
Hi @xhuan28!
No, currently IPP Crypto doesn't support GPU offloading (and there are no such short-term plans).
Please let us know if GPU offloading is important for your use-case. It would be great to know the application and crypto algorithm

**Comment by paveldyakov** [comment]
Hi @xhuan28, 
Can we close the question? 
It would be great if you can provide any GPU offloading use-cases that are important for you

**Comment by paveldyakov** [comment]
Hi @xhuan28, 

Could you please tell if the topic is still relevant for you?

**Comment by xhuan28** [comment]
Thanks for your reply. I think this question can be closed.
