### ISSUE TITLE
Does IPPCrypto have optimizations of curve25519 for CPU without AVX512-IFMA (but has AVX2/512)

### ISSUE THREAD

**Issue by qwcai** [intel/cryptography-primitives#58]
Or can we combine the other operations (e.g., ECPoint ...) for utilizing AVX2 or AVX512?

**Comment by ElenaTyuleneva** [comment]
Hello @qwcai,
Currently, we have curve25519 digital signature and key exchange schemes optimized only with AVX512-IFMA instructions (multi-buffer implementation).

Please, let us know if AVX-2/AVX-512 implementation of this curve is critical for you.

**Comment by qwcai** [comment]
Thanks for reply, I do need AVX-2/AVX-512 implementation of 25519 for graceful performance degradation, when AVX512-IFMA is not provided (As we have multiple different CPUs and cannot control which one will be provided).

Indeed, I only need the interface (GFpECMulPoint). 

However, I find that the provided function only supports the curve in form y^2=x^3+ax+b, instead of y^2=x^3+ax^2+bx for curve 25519.

Do you have any suggestion for this? Thanks

**Comment by ElenaTyuleneva** [comment]
I think we need more details to evaluate your request.
 
1. Are you interested in single-buffer [ippcp library](https://www.intel.com/content/www/us/en/docs/ipp-crypto/developer-reference/2022-2/basic-features.html)(`ipps*` APIs) or in multi-buffer [crypto_mb](https://www.intel.com/content/www/us/en/docs/ipp-crypto/developer-reference/2022-2/multi-buffer-cryptography-functions.html) library(`mbx_*` APIs) ? 
2. Key exchange mechanism based on curve25519 is presented only in the multi-buffer library (`mbx_x25519_mb8()`), which is utilizing one of the latest Intel HW - IceLake - and is highly optimized with AVX512-IFMA instruction. 
  Regarding the ippcp library, as you correctly noticed, only standard curves are supported, there is no support for curve25519 at all.
3. Could you please provide more information about your application? What is the use-case you are working on? Are you using ifma-based implementation now? It would be great if you can attach a sample showing how IPP Crypto is used in your app.

**Comment by qwcai** [comment]
Thanks for replies.

For Q1, in fact I just want to use Intel AVX2/512 for optimizing scalar multiplication, not matter ipps* APIs or mbx_* APIs.  If I have any mistake about single_buffer or multi-buffer, please help to point out. 

For Q3, I use curve 25519 for ECDH PSI (https://blog.willclark.tech/tech/2020/06/19/psi-with-ecdh.html), which only needs  scalar multiplication.  Now, I use mbx_x25519_mb8 API for scalar multiplication. However, as not all CPUs have ifma, I can only use software implementation (e.g. libsodium https://github.com/jedisct1/libsodium) for these CPUs, which has AVX2/AVX512.  Therefore, the performance has significantly degradation (about 3x). I want to try to improve the performance in these CPUs (has AVX2/512 but not ifma).

Is this potential performance improvement possible？Looking forward for your professional advice.

**Comment by ElenaTyuleneva** [comment]
>  If I have any mistake about single_buffer or multi-buffer, please help to point out.

Yes, I've noticed some inconsistency in your request since GFpECMulPoint API that you mentioned is the single-buffer, but the API you are using now(`mbx_x25519_mb8` ) is the multi-buffer one. They are the parts of two absolutely different libraries designed for different purposes.

> Is this potential performance improvement possible？Looking forward for your professional advice.

Unfortunately, we haven't evaluated AVX2/512 optimization for this specific curve, so I cannot provide you with a quick answer.
