### ISSUE TITLE
Add a GM SM2 key exchange protocol(not ECDH) to ipp-crypto

### ISSUE THREAD

**Issue by xiaonan-INTC** [intel/cryptography-primitives#72]
Hi Guys,

Current GM SM2 encrypt/decrypt algorithm using IPP Crypto has 2 sets of APIs:
- **ippsGFpECE*_SM2** with ECC ECDH Key exchange and encrypt/decrypt data
- **ippsGFpECE*_SM2_Ext** directly encrypt and decrypt data

Do you consider to add a GM SM2 key exchange protocol(not ECDH) to ipp-crypto?

**Comment by xiaonan-INTC** [comment]
Could some guys from IPP Crypto team help check this requirement? :)

**Comment by paveldyakov** [comment]
Hi @xiaonan-INTC, 
Currently we have no plans in terms of additional SM2 algorithms support.
Could you please provide more details? Link to the specification, other important aspects?

**Comment by xiaonan-INTC** [comment]
> Hi @xiaonan-INTC, Currently we have no plans in terms of additional SM2 algorithms support. Could you please provide more details? Link to the specification, other important aspects?

OK, @paveldyakov 

- ippsGFpECE_SM2*(ippsGFpECESEncrypt_SM2, ippsGFpECESDecrypt_SM2) with ECC ECDH Key exchange and encrypt/decrypt data
This is IEEE version, standard is IEEE Std 1363A-2004, link is:
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=1335427

- ippsGFpECE_SM2_Ext*(ippsGFpECEncryptSM2_Ext, ippsGFpECDecryptSM2_Ext) directly encrypt and decrypt data
This is GM version, standard is GM/T 0003-2012, link is:
https://gist.github.com/romen/d752b8d1897bc1a0009017511770de06 
https://datatracker.ietf.org/doc/html/draft-shen-sm2-ecdsa-02#section-7

**Comment by xiaonan-INTC** [comment]
Dear @paveldyakov 

Sorry to trouble, could you help estimate feasibility and workload of this requirement?

**Comment by paveldyakov** [comment]
Hi @xiaonan-INTC, 

Sorry for the delay in response. I will sync up with you regarding additional details

**Comment by xiaonan-INTC** [comment]
> Hi @xiaonan-INTC,
> 
> Sorry for the delay in response. I will sync up with you regarding additional details

After discussion with paveldyakov, this requirement would not be enabled in the nearest feature, so close it now and maybe reopen it some day. :)
