### ISSUE TITLE
Which APIs could replace those deprecated ones in ipp-crypto?

### ISSUE THREAD

**Issue by xiaonan-INTC** [intel/cryptography-primitives#74]
Dear ipp-crypto developers,

As a user of ipp-crypto, I saw many APIs in ipp-crypto/include/ippcp.h are marked as "IPP_DEPRECATED()", just want to know what does it mean, not recommended, will be deleted, or others? And which APIs could replace those deprecated ones if needed?

Below are what I am using and marked as "IPP_DEPRECATED()":
ECC point related:
ippsECCPPointGetSize
ippsECCPPointInit
ippsECCPGetPoint

ECC key related:
ippsECCPPublicKey
ippsECCPGenKeyPair
ippsECCPSetKeyPair

ECC SM2 creation/signing/verification:
ippsECCPGetSizeStdSM2
ippsECCPInitStdSM2
ippsECCPSetStdSM2
ippsECCPSignSM2
ippsECCPVerifySM2

SM3 message digest:
ippsSM3GetSize
ippsSM3Init
ippsSM3Update
ippsSM3GetTag
ippsSM3Final

**Comment by paveldyakov** [comment]
Hi @xiaonan-INTC, 

Thank you for the question. The list of deprecated functions (and suggested alternatives) you can find here https://www.intel.com/content/www/us/en/docs/ipp-crypto/developer-guide-reference/2021-10/removed-functions.html

Deprecation means that these functions will be removed in some future releases of IPP Cryptography and we highly recommend to switch customers' applications to the suggested alternatives 

Please let us know if you have any more questions

**Comment by xiaonan-INTC** [comment]
> Hi @xiaonan-INTC,
> 
> Thank you for the question. The list of deprecated functions (and suggested alternatives) you can find here https://www.intel.com/content/www/us/en/docs/ipp-crypto/developer-guide-reference/2021-10/removed-functions.html
> 
> Deprecation means that these functions will be removed in some future releases of IPP Cryptography and we highly recommend to switch customers' applications to the suggested alternatives
> 
> Please let us know if you have any more questions

It's clear, thanks a lot, paveldyakov!
