### ISSUE TITLE
typo: x84

### ISSUE THREAD

**Issue by bingzhux** [intel/cryptography-primitives#75]
See this diagram: https://github.com/intel/ipp-crypto/blob/develop/README_FIPS.md

x84 CPU HW should be x86 CPU HW ?

**Comment by aelizaro** [comment]
Hi @bingzhux, thanks for the notice! Yes, it is a typo, we will fix it.

**Comment by paveldyakov** [comment]
Hi @bingzhux, the typo has been fixed - you can check it in develop branch
