### ISSUE TITLE
Unclear usage of nScalars in ippsGFpECScratchBufferSize()

### ISSUE THREAD

**Issue by xiaonan-INTC** [intel/cryptography-primitives#77]
Refer to guidance(ipp-crypto_developer-guide-reference_2021.9)/source code(ipp-crypto/sources/ippcp/pcpgfpecbufsize.c),
In function: IppStatus ippsGFpECScratchBufferSize(int nScalars, const IppsGFpECState* pEC, int* pBufferSize);
Usage of parameter **nScalars** is not clear and without explanation, could add it to guidance/source code?

**Comment by paveldyakov** [comment]
Hi @xiaonan-INTC, sorry for the delay in response.
Let us investigate your question

**Comment by ElenaTyuleneva** [comment]
Hi @xiaonan-INTC , the required value of the `nScalars` passed into  `ippsGFpECScratchBufferSize` depends on the processing API used after - different processing functions require different scratchBuffer.

 We've updated the documentation with this guidance for each processing API, it will be available in the next product release. 

If you write me down which API sequence you are using, I can answer you here directly. 

_Elena_

**Comment by xiaonan-INTC** [comment]
> updated the documentation with this guidance for each processing API,

Thanks, ElenaTyuleneva, I will refer to the documentation of next product release, that is OK.
