### ISSUE TITLE
FIPS README Level 1 Requirements Typo 

### ISSUE THREAD

**Issue by Ibrahim00Assaf** [intel/cryptography-primitives#78]
In the Level 1 Requirements, Requirement # 7 specifies "_Module to guarantee uniqueness of GSM key + IV_". I am assuming this is not pertaining to Global System for Mobile Connections but rather Galois/Counter Mode. 
![Capture](https://github.com/intel/ipp-crypto/assets/170474877/c8e68bb8-7657-4bb2-aa04-dd5b1ee90bc2)

**Comment by aelizaro** [comment]
@Ibrahim00Assaf, thank you for catching the issue and your interest in ipp-crypto project, we will fix this typo!

**Comment by paveldyakov** [comment]
Hi @Ibrahim00Assaf, the typo has been fixed. Are you fine to close the issue?

**Comment by paveldyakov** [comment]
Closed the issue because of no response
