### ISSUE TITLE
Released binaries should include IPPCPConfig.cmake

### ISSUE THREAD

**Issue by morrowa** [intel/cryptography-primitives#8]
Adding a modern target-based CMake config file to the released binaries would allow developers to link against IPPCP with a simple `find_package` call in their own projects' CMakeLists.txt.

**Comment by amatyuko-intc** [comment]
Hello Andrew,

Thank you for the suggestion. We recently added FindIPPCrypto.cmake module to use with `find_package`, you can find it in the examples/ folder.  We also included it in to the upcoming binaries release.

Regards,
Andrey

**Comment by amatyuko-intc** [comment]
The binary packages starting from IPP Crypto 2020 Update 1 contain FindIPPCrypto.cmake in their examples/ folder. It can also be found in the repository [here](https://github.com/intel/ipp-crypto/blob/develop/examples/FindIPPCrypto.cmake).

If you have any issues with it, please let us know.

Regards,
Andrey
