### ISSUE TITLE
The SHA-512 feature selection macros are confusingly named

### ISSUE THREAD

**Issue by taviso** [intel/cryptography-primitives#87]
This looks like a typo, but I notice the same spelling is used in some filenames, so maybe it's intentional?

https://github.com/intel/cryptography-primitives/blob/944aa7af375dcfca091a13c032d996e3737be0c3/sources/ippcp/asm_intel64/pcpvariant.inc#L143

**Comment by stanciuadrian** [comment]
Hello @taviso,
Thank you for letting us know about the macro names.
We'll provide a fix in one of the next source code updates.

**Comment by stanciuadrian** [comment]
@taviso, we have provided a patch in a recent source code drop on the `develop` branch.
