### ISSUE TITLE
Fix `nasm` includes

### ISSUE THREAD

**Issue by bsdinis** [intel/cryptography-primitives#9]
When building for Linux, `nasm` include directories come without a trainling slash;
This goes against the `nasm` man page:

```
 -I|-i directory
           Adds a directory to the search path for include files. The
           directory specification must include the trailing slash, as
           it will be directly prepended to the name of the include
           file.
```

**Comment by amatyuko** [comment]
This is probably a bug in the NASM documentation, as trailing slashes are not required as of NASM 2.14.
See NASM bug report: https://bugzilla.nasm.us/show_bug.cgi?id=3392205

Regards,
Andrey
